= bespoke-PLUGIN_NAME
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
//ifdef::env-github[:badges:]
// Variables:
:release-version: master
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-PLUGIN_NAME/{release-version}

ifdef::badges[]
image:https://img.shields.io/npm/v/bespoke-PLUGIN_NAME.svg[npm package, link=https://www.npmjs.com/package/bespoke-PLUGIN_NAME]
image:https://img.shields.io/travis/opendevise/bespoke-PLUGIN_NAME/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-PLUGIN_NAME]
endif::[]

PLUGIN_DESCRIPTION

== Example

//http://opendevise.github.io/bespoke-PLUGIN_NAME[View the demo] online.

This repository includes a demo folder that shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-PLUGIN_NAME && cd bespoke-PLUGIN_NAME

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-PLUGIN_NAME.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-PLUGIN_NAME.js[development mode version], or use a package manager.

=== npm

 $ npm install bespoke-PLUGIN_NAME

=== Bower

 $ bower install bespoke-PLUGIN_NAME

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  PLUGIN_NAME = require('bespoke-PLUGIN_NAME');

bespoke.from('.deck', [
  PLUGIN_NAME()
]);
```

When using a browser global:

```js
bespoke.from('.deck', [
  bespoke.plugins.PLUGIN_NAME()
]);
```

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
